OPENAI_API_KEY : 
OPENAI_MODEL_NAME : "gpt-4o"

TAVILY_API_KEY : 

LANGCHAIN_TRACING_V2 :  "true"
LANGCHAIN_ENDPOINT : https://api.smith.langchain.com
LANGCHAIN_API_KEY : 
LANGCHAIN_PROJECT : Hierarchical Multi-Agent System
